"""Present so pytest puts the repo root on sys.path and `forecasting` imports.

Also holds the one shared skip rule for tests that run the real forecasting
tools: those need artifacts that are gitignored and regenerated by
`python -m scripts.setup`, so a fresh clone must skip them rather than fail.
"""

import pytest


def missing_forecast_artifacts() -> list[str]:
    """Names of runtime inputs the forecast/heat/crop tools need but lack."""
    from forecasting import config

    paths = [config.HORIZON_MANIFEST_PATH]
    for region in config.REGIONS:
        paths += [config.raw_path(region), config.daily_path(region),
                  config.scaler_path(region), config.spi_params_path(region),
                  *(config.horizon_model_path(region, h) for h in (1, 2, 3))]
    return [p.name for p in paths if not p.exists()]


@pytest.fixture
def forecast_artifacts():
    missing = missing_forecast_artifacts()
    if missing:
        pytest.skip(f"forecast artifacts missing ({', '.join(missing[:3])}"
                    f"{'...' if len(missing) > 3 else ''}) — run "
                    "`python -m scripts.setup`")
